/*===============================================参数定义========================================================*/
	#define De_SetPar_SetGreenPar										0x0000			//设置
	#define De_SetPar_SetGreenWord										0x0001			//设置界面文字
	#define De_SetPar_SetListePhone										0x0100			//设置监听号码							
	#define De_SetPar_SetResetPhone										0x0101			//设置电话复位
	#define De_SetPar_SetCerSevPhone 									0x0102			//设置短信中心服务号码
	#define De_SetPar_SetCenPhone										0x0103			//设置短信中心
	#define De_SetPar_SetAPN											0x0200			//设置APN参数
	#define De_SetPar_SetMastIP											0x0201			//设置主中心IP
	#define De_SetPar_SetMastDomainName									0x0202			//设置主域名
	#define De_SetPar_SetReserveIP										0x0203			//设置副中心IP
	#define De_SetPar_SetReserveDomainName								0x0204			//设置设置副域名
	#define De_SetPar_SetCenPort										0x0205			//设置中心端口号
	#define De_SetPar_SetCentHeart										0x0206			//中心下发心跳间隔
	#define De_SetPar_SetUseName										0x0207			//设置用户名
	#define De_SetPar_SetUsePass										0x0208			//设置拨号密码
	#define De_SetPar_SetDevHeart										0x0209			//终端上发心跳间隔
	
	#define De_SetPar_SetComMod											0x020a			//设置通讯方式
	#define De_SetPar_SetIPRepeat										0x020b			//Ip关键指令重发次数
	#define De_SetPar_SetIPRepeatTime									0x020c			//IP关键指令重发间隔时间
	#define De_SetPar_SetMessageRepeat									0x020d			//Message关键指令重发次数
	#define De_SetPar_SetMessageRepeatTimer								0x020e			//Message Timer 重发时间
	#define De_SetPar_SetIPTransSms										0x020f			//Message与IP之间切换时间
	#define De_SetPar_SetDataLog										0x0210			//数据日志存储
	#define De_SetPar_SetDataScotomaLog									0x0211			//盲区补偿数据
	#define De_SetPar_SetParLoad										0x0212			//设置上传参数
	#define De_SetPar_SetWireLessPar									0x0213			//设置无线参数
	#define De_SetPar_SetDePassWord										0x0301			//设置终端密码
	#define De_SetPar_ComFac											0x0302			//回复出厂值
	#define De_SetPar_SetAccTimer										0x0303			//设置ACC累计时间
	#define De_SetPar_SetRunLen											0x0304			//设置运行里程
	#define De_SetPar_SetPerPuse										0x0305			//设置每周的脉冲数
	#define De_SetPar_SetCarFeature										0x0306			//设置车辆特征
	#define De_SetPar_SetTakeLCD										0x0307			//设置车辆是否安装调度
	#define De_SetPar_SetOilFrequency									0x0308			//设置油量采样频率
	#define De_SetPar_SetSleepTimer										0x0309			//设置休眠时间
	#define De_SetPar_SetCloseTimer										0x030a			//设置关机时间
	#define De_SetPar_SetLogMess										0x030b			//设置登录提示
	#define De_SetPar_SetTaskVid										0x030c			//设置是否安装摄像头
	#define De_SetPar_SetHighSpeed										0x0400			//设置超速报警
	#define De_SetPar_SetLowSpeed										0x0401			//设置低速报警
	#define De_SetPar_SetLowVlt											0x0402			//设置低电压报警
	#define De_SetPar_SetVidType										0x0500			//设置拍照类型
	#define De_SetPar_SetOrderFrmTimer									0x0600			//设置预约订单时间
	#define De_SetPar_HardWareEdit										0x0700			//查询硬件版本
	#define De_SetPar_SoftWareEdit										0x0701			//查询软件版本
	#define De_SetPar_MachID											0X0702			//查询机器编号
	#define De_SetPar_Menum												0x0703			//查询菜单信息
	#define De_SetPar_Phone												0x0704			//查询固定电话信息
	#define De_SetPar_ConfineCall										0x0705			//查询通话限制状态
	#define De_SetPar_DriverID											0X0706			//查询驾驶员
	#define De_SetPar_DriverLogin										0x0707			//查询已登录的驾驶员
/*===============================================参数定义位置表=================================================*/
	#define De_AgreeOn_SetPar_State_SetGreenPar							0 				//设置
	#define De_AgreeOn_SetPar_State_SetGreenWord						1 				//设置界面文字
	#define De_AgreeOn_SetPar_State_SetListePhone						2				//设置监听号码							
	#define De_AgreeOn_SetPar_State_SetResetPhone						3				//设置电话复位
	#define De_AgreeOn_SetPar_State_SetCerSevPhone 						4				//设置短信中心服务号码
	#define De_AgreeOn_SetPar_State_SetCenPhone							5				//设置短信中心
	#define De_AgreeOn_SetPar_State_SetAPN								6				//设置APN参数
	#define De_AgreeOn_SetPar_State_SetMastIP							7				//设置主中心IP
	#define De_AgreeOn_SetPar_State_SetMastDomainName					8				//设置主域名
	#define De_AgreeOn_SetPar_State_SetReserveIP						9				//设置副中心IP
	#define De_AgreeOn_SetPar_State_SetReserveDomainName				10				//设置设置副域名
	#define De_AgreeOn_SetPar_State_SetCenPort							11				//设置中心端口号
	#define De_AgreeOn_SetPar_State_SetUseName							12				//设置用户名
	#define De_AgreeOn_SetPar_State_SetUsePass							13				//设置拨号密码
	#define De_AgreeOn_SetPar_State_SetDevHeart							14				//终端上发心跳间隔
	#define De_AgreeOn_SetPar_State_SetCentHeart						15				//中心下发心跳间隔
	#define De_AgreeOn_SetPar_State_SetComMod							16				//设置通讯方式
	#define De_AgreeOn_SetPar_State_SetIPRepeat							17				//Ip关键指令重发次数
	#define De_AgreeOn_SetPar_State_SetIPRepeatTime						18				//IP关键指令重发间隔时间
	#define De_AgreeOn_SetPar_State_SetMessageRepeat					19				//Message关键指令重发次数
	#define De_AgreeOn_SetPar_State_SetMessageRepeatTimer				20				//Message Timer 重发时间
	#define De_AgreeOn_SetPar_State_SetIPTransSms						21				//Message与IP之间切换时间
	#define De_AgreeOn_SetPar_State_SetDataLog							22				//数据日志存储
	#define De_AgreeOn_SetPar_State_SetDataScotomaLog					23				//盲区补偿数据
	#define De_AgreeOn_SetPar_State_SetParLoad							24				//设置上传参数
	#define De_AgreeOn_SetPar_State_SetWireLessPar						25				//设置无线参数
	#define De_AgreeOn_SetPar_State_SetDePassWord						26				//设置终端密码
	#define De_AgreeOn_SetPar_State_SetComFac							27				//回复出厂值
	#define De_AgreeOn_SetPar_State_SetAccTimer							28				//设置ACC累计时间
	#define De_AgreeOn_SetPar_State_SetRunLen							29				//设置运行里程
	#define De_AgreeOn_SetPar_State_SetPerPuse							30				//设置每周的脉冲数
	#define De_AgreeOn_SetPar_State_SetCarFeature						31				//设置车辆特征
	#define De_AgreeOn_SetPar_State_SetTakeLCD							32				//设置车辆是否安装调度
	#define De_AgreeOn_SetPar_State_SetOilFrequency						33				//设置油量采样频率
	#define De_AgreeOn_SetPar_State_SetSleepTimer						34				//设置休眠时间
	#define De_AgreeOn_SetPar_State_SetCloseTimer						35				//设置关机时间
	#define De_AgreeOn_SetPar_State_SetLogMess							36				//设置登录提示
	#define De_AgreeOn_SetPar_State_SetTaskVid							37				//设置是否安装摄像头
	#define De_AgreeOn_SetPar_State_SetHighSpeed						38				//设置超速报警
	#define De_AgreeOn_SetPar_State_SetLowSpeed							39				//设置低速报警
	#define De_AgreeOn_SetPar_State_SetLowVlt							40				//设置低电压报警
	#define De_AgreeOn_SetPar_State_SetVidType							41				//设置拍照类型
	#define De_AgreeOn_SetPar_State_SetOrderFrmTimer					42				//设置预约订单时间
	#define De_AgreeOn_SetPar_State_SetHardWareEdit						43				//查询硬件版本
	#define De_AgreeOn_SetPar_State_SetSoftWareEdit						44				//查询软件版本
	#define De_AgreeOn_SetPar_State_SetMachID							45				//查询机器编号
	#define De_AgreeOn_SetPar_State_SetMenum							46				//查询菜单信息
	#define De_AgreeOn_SetPar_State_SetPhone							47				//查询固定电话信息
	#define De_AgreeOn_SetPar_State_SetConfineCall						48				//查询通话限制状态
	#define De_AgreeOn_SetPar_State_SetDriverID							49				//查询驾驶员
	#define De_AgreeOn_SetPar_State_SetDriverLogin						50				//查询已登录的驾驶员
	#define De_AgreeOn_SetPar_Number									De_AgreeOn_SetPar_State_SetDriverLogin+1

